--- #YAML:1.0
name:               Data-Beacon
version:            0.2.1
abstract:           BEACON format validating parser and serializer
author:
    - Jakob Voss <jakob.voss@gbv.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Validate::URI:  0
    Getopt::Long:         0
    Pod::Usage:           0
    Time::Piece:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
