---
abstract: 'BEACON format validating parser and serializer'
author:
  - 'Jakob Voß'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Beacon
requires:
  Carp: 0
  Exporter: 0
  Getopt::Long: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Time::Piece: 0
  URI::Escape: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/nichtich/Data-Beacon/issues
  homepage: https://github.com/nichtich/Data-Beacon
  repository: https://github.com/nichtich/Data-Beacon.git
version: 0.3.1
